version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/customer_support
      - JWT_SECRET_KEY=your-secret-key-here
      - GROQ_API_KEY=your-groq-api-key-here
    depends_on:
      - db
    volumes:
      - .:/app
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer_support
    ports:
      - "5432:5432"

volumes:
  postgres_data: 